name: Go

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        GO_VERSION:
          - "1.16.x"
          - "1.20.x"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.GO_VERSION }}
      uses: actions/setup-go@v2
      with:
        go-version: "${{ matrix.GO_VERSION }}"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
